name: student-api-github-ci
on: [push]
jobs:
   check-bats-version:
   runs-on: ubuntu-latest
   steps:
    -uses: action/checkout@v2
    -uses: action/setup-node@v1
    -run: npm install -g bats
    -run: bats -v